#!/usr/bin/env python
import interpreter, sys

try:
  if len(sys.argv) is 1: # interactive shell
    while True:
      result = interpreter.interpret(raw_input('>> '))
      if result is not None:
        print result
  else: # run file
    try:
      f = open(sys.argv[1])
      for line in f:
        interpreter.interpret(line)
    except IOError:
      print 'No such file.'
except (KeyboardInterrupt, EOFError):
  print