expression = number , ( operator , number ) ;
operator = [ "+" | "-" | "*" | "/" ] ;
# FIXME: number regexp doesn't catch ".x" ;
number = ? \d(\.\d*)? ? ;
manyblas = { "bla" , ( " " ) } , ( "bloop" ) ;
