assignment_statement = variable , assignment_op, expression ;
expression = number , ( operator , number ) ;
operator = [ "+" | "-" | "*" | "/" ] ;
# FIXME: number regexp doesn't catch ".x" ;
number = ? \d(\.\d*)? ? ;
variable = ? [a-zA-Z] ? , { ? [a-zA-Z0-9] ? } ;
assignment_op = "=" ;
